apiVersion: v1
kind: ConfigMap
metadata:
  name: container-registry-cm
  namespace: cr
data:
  config.yml: |
    version: 0.1
    log:
      fields:
        service: registry
    storage:
      cache:
        blobdescriptor: inmemory
      filesystem:
        rootdirectory: /var/lib/registry
        maxthreads: 100
      maintenance:
        enabled: yourself
        age: 24h
        interval: 48h
        dryrun: false
    http:
      addr: :5000
      host: https://cr.federico-paolillo.xyz
      relativeurls: false
    auth:
      htpasswd:
        realm: basic-realm
        path: /etc/registry/htpasswd
    health:
      storagedriver:
        enabled: true
        interval: 10s
        threshold: 3
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: container-registry-users
  namespace: cr
data:
  htpasswd: | # generate more lines using htpasswd -B
    crboy:$2y$05$a/pAtF5rX9eJmf6ZqFXXJuR0xlNg9eC5H/kPZxOzxDOXKK2BrVqjO
