apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: container-registry-storage-pvc
  namespace: cr
spec:
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
